INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('A00','A09','Doenças infecciosas intestinais','Doenças infecciosas intestinais');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('A15','A19','Tuberculose','Tuberculose');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('A20','A28','Algumas doenças bacterianas zoonóticas','Algumas doenças bacterianas zoonóticas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('A30','A49','Outras doenças bacterianas','Outras doenças bacterianas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('A50','A64','Infecções de transmissão predominantemente sexual','Infecções de transmissão predominantemente sexual');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('A65','A69','Outras doenças por espiroquetas','Outras doenças por espiroquetas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('A70','A74','Outras doenças causadas por clamídias','Outras doenças causadas por clamídias');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('A75','A79','Rickettsioses','Rickettsioses');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('A80','A89','Infecções virais do sistema nervoso central','Infecções virais do sistema nervoso central');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('A90','A99','Febres por arbovírus e febres hemorrágicas virais','Febres por arbovírus e febres hemorrágicas virais');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('B00','B09','Infecções virais caracterizadas por lesões de pele e mucosas','Infecções virais caract p/lesões de pele e mucosas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('B15','B19','Hepatite viral','Hepatite viral');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('B20','B24','Doença pelo vírus da imunodeficiência humana [HIV]','Doença pelo vírus da imunodeficiência humana [HIV]');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('B25','B34','Outras doenças por vírus','Outras doenças por vírus');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('B35','B49','Micoses','Micoses');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('B50','B64','Doenças devidas a protozoários','Doenças devidas a protozoários');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('B65','B83','Helmintíases','Helmintíases');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('B85','B89','Pediculose, acaríase e outras infestações','Pediculose, acaríase e outras infestações');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('B90','B94','Seqüelas de doenças infecciosas e parasitárias','Seqüelas de doenças infecciosas e parasitárias');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('B95','B97','Agentes de infecções bacterianas, virais e outros agentes infecciosos','Agentes infec bacter, virais e outr agentes infecc');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('B99','B99','Outras doenças infecciosas','Outras doenças infecciosas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C00','C97','Neoplasias [tumores] malignas(os)','Neoplasias malignas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C00','C75','Neoplasias [tumores] malignas(os), declaradas ou presumidas como primárias, de localizações especificadas, exceto dos tecidos linfático, hematopoético e tecidos correlatos','Neoplasias malignas de localizações especificadas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C00','C14','Neoplasias malignas do lábio, cavidade oral e faringe','Neoplasias malig do lábio, cavidade oral e faringe');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C15','C26','Neoplasias malignas dos órgãos digestivos','Neoplasias malignas dos órgãos digestivos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C30','C39','Neoplasias malignas do aparelho respiratório e dos órgãos intratorácicos','Neopl malig aparelho respirat e órgãos intratorác');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C40','C41','Neoplasias malignas dos ossos e das cartilagens articulares','Neopl malig dos ossos e cartilagens articulares');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C43','C44','Melanoma e outras(os) neoplasias malignas da pele','Melanoma e outras(os) neoplasias malignas da pele');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C45','C49','Neoplasias malignas do tecido mesotelial e tecidos moles','Neopl malig do tecido mesotelial e tecidos moles');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C50','C50','Neoplasias malignas da mama','Neoplasias malignas da mama');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C51','C58','Neoplasias malignas dos órgãos genitais femininos','Neoplasias malignas dos órgãos genitais femininos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C60','C63','Neoplasias malignas dos órgãos genitais masculinos','Neoplasias malignas dos órgãos genitais masculinos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C64','C68','Neoplasias malignas do trato urinário','Neoplasias malignas do trato urinário');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C69','C72','Neoplasias malignas dos olhos, do encéfalo e de outras partes do sistema nervoso central','Neopl malig olhos encéf outr part sist nerv centr');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C73','C75','Neoplasias malignas da tireóide e de outras glândulas endócrinas','Neopl malig tireóide e outras glândulas endócrinas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C76','C80','Neoplasias malignas de localizações mal definidas, secundárias e de localizações não especificadas','Neopl malig local mal def, secund e local n espec');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C81','C96','Neoplasias [tumores] malignas(os), declaradas ou presumidas como primárias, dos tecidos linfático, hematopoético e tecidos correlatos','Neopl malig tecido linfát hematopoét e correlatos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('C97','C97','Neoplasias malignas de localizações múltiplas independentes (primárias)','Neopl malig local múltiplas independentes (prim)');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('D00','D09','Neoplasias [tumores] in situ','Neoplasias [tumores] in situ');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('D10','D36','Neoplasias [tumores] benignas(os)','Neoplasias [tumores] benignas(os)');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('D37','D48','Neoplasias [tumores] de comportamento incerto ou desconhecido','Neopl de comportamento incerto ou desconhecido');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('D50','D53','Anemias nutricionais','Anemias nutricionais');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('D55','D59','Anemias hemolíticas','Anemias hemolíticas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('D60','D64','Anemias aplásticas e outras anemias','Anemias aplásticas e outras anemias');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('D65','D69','Defeitos da coagulação, púrpura e outras afecções hemorrágicas','Defeitos coagulação, púrpura, outr afecç hemorrág');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('D70','D77','Outras doenças do sangue e dos órgãos hematopoéticos','Outras doenças do sangue e órgãos hematopoéticos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('D80','D89','Alguns transtornos que comprometem o mecanismo imunitário','Alguns transt q comprometem o mecanismo imunitário');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('E00','E07','Transtornos da glândula tireóide','Transtornos da glândula tireóide');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('E10','E14','Diabetes mellitus','Diabetes mellitus');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('E15','E16','Outros transtornos da regulação da glicose e da secreção pancreática interna','Outr transt regulação glicose e secr pancreát int');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('E20','E35','Transtornos de outras glândulas endócrinas','Transtornos de outras glândulas endócrinas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('E40','E46','Desnutrição','Desnutrição');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('E50','E64','Outras deficiências nutricionais','Outras deficiências nutricionais');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('E65','E68','Obesidade e outras formas de hiperalimentação','Obesidade e outras formas de hiperalimentação');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('E70','E90','Distúrbios metabólicos','Distúrbios metabólicos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('F00','F09','Transtornos mentais orgânicos, inclusive os sintomáticos','Transtornos mentais orgânicos, incl sintomáticos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('F10','F19','Transtornos mentais e comportamentais devidos ao uso de substância psicoativa','Transt ment e comport dev ao uso subst psicoativa');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('F20','F29','Esquizofrenia, transtornos esquizotípicos e transtornos delirantes','Esquizofrenia, transt esquizotípicos e delirantes');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('F30','F39','Transtornos do humor [afetivos]','Transtornos do humor [afetivos]');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('F40','F48','Transtornos neuróticos, transtornos relacionados com o "stress" e transtornos somatoformes','Transt neuróticos, relacion stress e somatoformes');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('F50','F59','Síndromes comportamentais associadas a disfunções fisiológicas e a fatores físicos','Síndr comport assoc disfunç fisiológ e fat físicos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('F60','F69','Transtornos da personalidade e do comportamento do adulto','Transtornos da personalidade e do comport adulto');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('F70','F79','Retardo mental','Retardo mental');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('F80','F89','Transtornos do desenvolvimento psicológico','Transtornos do desenvolvimento psicológico');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('F90','F98','Transtornos do comportamento e transtornos emocionais que aparecem habitualmente durante a infância ou a adolescência','Transt compor e emoc q aparecem dur infânc adolesc');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('F99','F99','Transtorno mental não especificado','Transtorno mental não especificado');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('G00','G09','Doenças inflamatórias do sistema nervoso central','Doenças inflamatórias do sistema nervoso central');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('G10','G13','Atrofias sistêmicas que afetam principalmente o sistema nervoso central','Atrofias sistêm q afetam princ o sist nerv central');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('G20','G26','Doenças extrapiramidais e transtornos dos movimentos','Doenças extrapiramidais e transt dos movimentos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('G30','G32','Outras doenças degenerativas do sistema nervoso','Outras doenças degenerativas do sistema nervoso');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('G35','G37','Doenças desmielinizantes do sistema nervoso central','Doenças desmielinizantes do sist nervoso central');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('G40','G47','Transtornos episódicos e paroxísticos','Transtornos episódicos e paroxísticos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('G50','G59','Transtornos dos nervos, das raízes e dos plexos nervosos','Transtornos dos nervos, raízes e plexos nervosos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('G60','G64','Polineuropatias e outros transtornos do sistema nervoso periférico','Polineuropatias e outr transt sist nerv periférico');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('G70','G73','Doenças da junção mioneural e dos músculos','Doenças da junção mioneural e dos músculos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('G80','G83','Paralisia cerebral e outras síndromes paralíticas','Paralisia cerebral e outras síndromes paralíticas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('G90','G99','Outros transtornos do sistema nervoso','Outros transtornos do sistema nervoso');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H00','H06','Transtornos da pálpebra, do aparelho lacrimal e da órbita','Transtornos pálpebra, aparelho lacrimal e órbita');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H10','H13','Transtornos da conjuntiva','Transtornos da conjuntiva');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H15','H22','Transtornos da esclerótica, da córnea, da íris e do corpo ciliar','Transtorn esclerótica, córnea, íris e corpo ciliar');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H25','H28','Transtornos do cristalino','Transtornos do cristalino');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H30','H36','Transtornos da coróide e da retina','Transtornos da coróide e da retina');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H40','H42','Glaucoma','Glaucoma');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H43','H45','Transtornos do humor vítreo e do globo ocular','Transtornos do humor vítreo e do globo ocular');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H46','H48','Transtornos do nervo óptico e das vias ópticas','Transtornos do nervo óptico e das vias ópticas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H49','H52','Transtornos dos músculos oculares, do movimento binocular, da acomodação e da refração','Transt músc oculares, movim binoc, acomod e refraç');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H53','H54','Transtornos visuais e cegueira','Transtornos visuais e cegueira');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H55','H59','Outros transtornos do olho e anexos','Outros transtornos do olho e anexos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H60','H62','Doenças do ouvido externo','Doenças do ouvido externo');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H65','H75','Doenças do ouvido médio e da mastóide','Doenças do ouvido médio e da mastóide');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H80','H83','Doenças do ouvido interno','Doenças do ouvido interno');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('H90','H95','Outros transtornos do ouvido','Outros transtornos do ouvido');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('I00','I02','Febre reumática aguda','Febre reumática aguda');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('I05','I09','Doenças reumáticas crônicas do coração','Doenças reumáticas crônicas do coração');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('I10','I15','Doenças hipertensivas','Doenças hipertensivas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('I20','I25','Doenças isquêmicas do coração','Doenças isquêmicas do coração');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('I26','I28','Doenças cardíaca pulmonar e da circulação pulmonar','Doenças cardíaca pulmonar e da circulação pulmonar');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('I30','I52','Outras formas de doença do coração','Outras formas de doença do coração');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('I60','I69','Doenças cerebrovasculares','Doenças cerebrovasculares');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('I70','I79','Doenças das artérias, das arteríolas e dos capilares','Doenças das artérias, das arteríolas e capilares');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('I80','I89','Doenças das veias, dos vasos linfáticos e dos gânglios linfáticos, não classificadas em outra parte','Doenças veias, vasos e gânglios linfáticos, NCOP');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('I95','I99','Outros transtornos, e os não especificados do aparelho circulatório','Outros transt e os não espec aparelho circulatório');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('J00','J06','Infecções agudas das vias aéreas superiores','Infecções agudas das vias aéreas superiores');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('J09','J18','Influenza [gripe] e pneumonia','Influenza [gripe] e pneumonia');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('J20','J22','Outras infecções agudas das vias aéreas inferiores','Outras infecções agudas das vias aéreas inferiores');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('J30','J39','Outras doenças das vias aéreas superiores','Outras doenças das vias aéreas superiores');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('J40','J47','Doenças crônicas das vias aéreas inferiores','Doenças crônicas das vias aéreas inferiores');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('J60','J70','Doenças pulmonares devidas a agentes externos','Doenças pulmonares devidas a agentes externos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('J80','J84','Outras doenças respiratórias que afetam principalmente o interstício','Outras doenças respirat q afetam princ interstício');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('J85','J86','Afecções necróticas e supurativas das vias aéreas inferiores','Afecções necróticas e supurat vias aéreas infer');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('J90','J94','Outras doenças da pleura','Outras doenças da pleura');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('J95','J99','Outras doenças do aparelho respiratório','Outras doenças do aparelho respiratório');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('K00','K14','Doenças da cavidade oral, das glândulas salivares e dos maxilares','Doenças cavidade oral, glând salivares e maxilares');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('K20','K31','Doenças do esôfago, do estômago e do duodeno','Doenças do esôfago, do estômago e do duodeno');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('K35','K38','Doenças do apêndice','Doenças do apêndice');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('K40','K46','Hérnias','Hérnias');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('K50','K52','Enterites e colites não-infecciosas','Enterites e colites não-infecciosas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('K55','K63','Outras doenças dos intestinos','Outras doenças dos intestinos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('K65','K67','Doenças do peritônio','Doenças do peritônio');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('K70','K77','Doenças do fígado','Doenças do fígado');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('K80','K87','Transtornos da vesícula biliar, das vias biliares e do pâncreas','Transt vesícula biliar, vias biliares e pâncreas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('K90','K93','Outras doenças do aparelho digestivo','Outras doenças do aparelho digestivo');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('L00','L08','Infecções da pele e do tecido subcutâneo','Infecções da pele e do tecido subcutâneo');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('L10','L14','Afecções bolhosas','Afecções bolhosas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('L20','L30','Dermatite e eczema','Dermatite e eczema');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('L40','L45','Afecções pápulo-descamativas','Afecções pápulo-descamativas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('L50','L54','Urticária e eritema','Urticária e eritema');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('L55','L59','Transtornos da pele e do tecido subcutâneo relacionados com a radiação','Transt pele e tecido subcutâneo relac c/radiação');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('L60','L75','Afecções dos anexos da pele','Afecções dos anexos da pele');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('L80','L99','Outras afecções da pele e do tecido subcutâneo','Outras afecções da pele e do tecido subcutâneo');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M00','M25','Artropatias','Artropatias');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M00','M03','Artropatias infecciosas','Artropatias infecciosas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M05','M14','Poliartropatias inflamatórias','Poliartropatias inflamatórias');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M15','M19','Artroses','Artroses');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M20','M25','Outros transtornos articulares','Outros transtornos articulares');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M30','M36','Doenças sistêmicas do tecido conjuntivo','Doenças sistêmicas do tecido conjuntivo');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M40','M54','Dorsopatias','Dorsopatias');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M40','M43','Dorsopatias deformantes','Dorsopatias deformantes');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M45','M49','Espondilopatias','Espondilopatias');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M50','M54','Outras dorsopatias','Outras dorsopatias');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M60','M79','Transtornos dos tecidos moles','Transtornos dos tecidos moles');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M60','M63','Transtornos musculares','Transtornos musculares');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M65','M68','Transtornos das sinóvias e dos tendões','Transtornos das sinóvias e dos tendões');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M70','M79','Outros transtornos dos tecidos moles','Outros transtornos dos tecidos moles');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M80','M94','Osteopatias e condropatias','Osteopatias e condropatias');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M80','M85','Transtornos da densidade e da estrutura óssea','Transtornos da densidade e da estrutura óssea');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M86','M90','Outras osteopatias','Outras osteopatias');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M91','M94','Condropatias','Condropatias');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('M95','M99','Outros transtornos do sistema osteomuscular e do tecido conjuntivo','Outr transt sist osteomuscular e tecido conjuntivo');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('N00','N08','Doenças glomerulares','Doenças glomerulares');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('N10','N16','Doenças renais túbulo-intersticiais','Doenças renais túbulo-intersticiais');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('N17','N19','Insuficiência renal','Insuficiência renal');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('N20','N23','Calculose renal','Calculose renal');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('N25','N29','Outros transtornos do rim e do ureter','Outros transtornos do rim e do ureter');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('N30','N39','Outras doenças do aparelho urinário','Outras doenças do aparelho urinário');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('N40','N51','Doenças dos órgãos genitais masculinos','Doenças dos órgãos genitais masculinos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('N60','N64','Doenças da mama','Doenças da mama');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('N70','N77','Doenças inflamatórias dos órgãos pélvicos femininos','Doenças inflamatórias órgãos pélvicos femininos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('N80','N98','Transtornos não-inflamatórios do trato genital feminino','Transt não-inflamatórios do trato genital feminino');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('N99','N99','Outros transtornos do aparelho geniturinário','Outros transtornos do aparelho geniturinário');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('O00','O08','Gravidez que termina em aborto','Gravidez que termina em aborto');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('O10','O16','Edema, proteinúria e transtornos hipertensivos na gravidez, no parto e no puerpério','Edema proteinúr e transt hipert gravid parto puerp');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('O20','O29','Outros transtornos maternos relacionados predominantemente com a gravidez','Outros transtornos maternos relac predom gravidez');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('O30','O48','Assistência prestada à mãe por motivos ligados ao feto e à cavidade amniótica e por possíveis problemas relativos ao parto','Assist à mãe mot feto cavid amniót e prob rel part');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('O60','O75','Complicações do trabalho de parto e do parto','Complicações do trabalho de parto e do parto');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('O80','O84','Parto','Parto');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('O85','O92','Complicações relacionadas predominantemente com o puerpério','Complicações relacionadas predom com o puerpério');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('O94','O99','Outras afecções obstétricas não classificadas em outra parte','Outras afecções obstétricas NCOP');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('P00','P04','Feto e recém-nascido afetados por fatores maternos e por complicações da gravidez, do trabalho de parto e do parto','Fet rec-nasc afet fat mat e compl grav, trab parto');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('P05','P08','Transtornos relacionados com a duração da gestação e com o crescimento fetal','Transt relac com a duração gestação e cresc fetal');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('P10','P15','Traumatismo de parto','Traumatismo de parto');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('P20','P29','Transtornos respiratórios e cardiovasculares específicos do período perinatal','Transt respirat e cardiovasc específ per perinatal');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('P35','P39','Infecções específicas do período perinatal','Infecções específicas do período perinatal');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('P50','P61','Transtornos hemorrágicos e hematológicos do feto e do recém-nascido','Transt hemorrág e hematológ feto e recém-nascido');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('P70','P74','Transtornos endócrinos e metabólicos transitórios específicos do feto e do recém-nascido','Transt endócr e metaból trans espec fet e rec-nasc');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('P75','P78','Transtornos do aparelho digestivo do feto ou do recém-nascido','Transt aparelho digestivo do feto ou recém-nascido');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('P80','P83','Afecções comprometendo o tegumento e a regulação térmica do feto e do recém-nascido','Afecç comprom tegument e reg térm fet e recém-nasc');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('P90','P96','Outros transtornos originados no período perinatal','Outros transtornos originados no período perinatal');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Q00','Q07','Malformações congênitas do sistema nervoso','Malformações congênitas do sistema nervoso');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Q10','Q18','Malformações congênitas do olho, do ouvido, da face e do pescoço','Malform congênitas do olho, ouvido, face e pescoço');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Q20','Q28','Malformações congênitas do aparelho circulatório','Malformações congênitas do aparelho circulatório');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Q30','Q34','Malformações congênitas do aparelho respiratório','Malformações congênitas do aparelho respiratório');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Q35','Q37','Fenda labial e fenda palatina','Fenda labial e fenda palatina');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Q38','Q45','Outras malformações congênitas do aparelho digestivo','Outras malformações congênitas aparelho digestivo');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Q50','Q56','Malformações congênitas dos órgãos genitais','Malformações congênitas dos órgãos genitais');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Q60','Q64','Malformações congênitas do aparelho urinário','Malformações congênitas do aparelho urinário');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Q65','Q79','Malformações e deformidades congênitas do sistema osteomuscular','Malform e deform congênit do sistema osteomuscular');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Q80','Q89','Outras malformações congênitas','Outras malformações congênitas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Q90','Q99','Anomalias cromossômicas não classificadas em outra parte','Anomalias cromossômicas NCOP');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('R00','R09','Sintomas e sinais relativos ao aparelho circulatório e respiratório','Sint e sinais relat aparelho circulat e respirat');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('R10','R19','Sintomas e sinais relativos ao aparelho digestivo e ao abdome','Sintom e sinais relat ao aparelho digest e abdome');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('R20','R23','Sintomas e sinais relativos à pele e ao tecido subcutâneo','Sintom e sinais relat à pele e tecido subcutâneo');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('R25','R29','Sintomas e sinais relativos aos sistemas nervoso e osteomuscular','Sint e sinais relat sist nervoso e osteomuscular');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('R30','R39','Sintomas e sinais relativos ao aparelho urinário','Sintomas e sinais relativos ao aparelho urinário');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('R40','R46','Sintomas e sinais relativos à cognição, à percepção, ao estado emocional e ao comportamento','Sint e sinais rel cogn percep estado emoc e compor');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('R47','R49','Sintomas e sinais relativos à fala e à voz','Sintomas e sinais relativos à fala e à voz');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('R50','R69','Sintomas e sinais gerais','Sintomas e sinais gerais');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('R70','R79','Achados anormais de exames de sangue, sem diagnóstico','Achados anormais exames de sangue, sem diagnóstico');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('R80','R82','Achados anormais de exames de urina, sem diagnóstico','Achados anormais exames de urina, sem diagnóstico');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('R83','R89','Achados anormais de exames e de outros líquidos, substâncias e tecidos do corpo, sem diagnóstico','Achad anorm exam e out líq, subs e tec corp s/diag');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('R90','R94','Achados anormais de exames para diagnóstico por imagem e em estudos de função, sem diagnóstico','Achad anorm exam diag imagem estud função, s/diag');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('R95','R99','Causas mal definidas e desconhecidas de mortalidade','Causas mal definidas e desconhecidas mortalidade');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('S00','S09','Traumatismos da cabeça','Traumatismos da cabeça');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('S10','S19','Traumatismos do pescoço','Traumatismos do pescoço');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('S20','S29','Traumatismos do tórax','Traumatismos do tórax');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('S30','S39','Traumatismos do abdome, do dorso, da coluna lombar e da pelve','Traumatismos abdome, dorso, coluna lombar e pelve');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('S40','S49','Traumatismos do ombro e do braço','Traumatismos do ombro e do braço');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('S50','S59','Traumatismos do cotovelo e do antebraço','Traumatismos do cotovelo e do antebraço');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('S60','S69','Traumatismos do punho e da mão','Traumatismos do punho e da mão');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('S70','S79','Traumatismos do quadril e da coxa','Traumatismos do quadril e da coxa');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('S80','S89','Traumatismos do joelho e da perna','Traumatismos do joelho e da perna');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('S90','S99','Traumatismos do tornozelo e do pé','Traumatismos do tornozelo e do pé');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T00','T07','Traumatismos envolvendo múltiplas regiões do corpo','Traumatismos envolvendo múltiplas regiões do corpo');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T08','T14','Traumatismos de localização não especificada do tronco, membro ou outra região do corpo','Traum local não espec tronco membro outr reg corpo');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T15','T19','Efeito da penetração de corpo estranho através de orifício natural','Efeito penetr corpo estranho através orif natural');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T20','T32','Queimaduras e corrosões','Queimaduras e corrosões');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T20','T25','Queimaduras e corrosões da superfície externa do corpo, especificadas por local','Queimad e corros superf ext corpo, espec p/local');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T26','T28','Queimaduras e corrosões limitadas ao olho e aos órgãos internos','Queimad e corrosões limit olho e órgãos internos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T29','T32','Queimaduras e corrosões de múltiplas regiões e de regiões não especificadas do corpo','Queimad e corrosões múlt reg e reg não espec corpo');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T33','T35','Geladuras [frostbite]','Geladuras [frostbite]');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T36','T50','Intoxicação por drogas, medicamentos e substâncias biológicas','Intox por drogas, medicamentos e subst biológicas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T51','T65','Efeitos tóxicos de substâncias de origem predominantemente não-medicinal','Efeitos tóxicos subst origem predom não-medicinal');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T66','T78','Outros efeitos de causas externas e os não especificados','Outros efeitos de causas externas e os não espec');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T79','T79','Algumas complicações precoces de traumatismos','Algumas complicações precoces de traumatismos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T80','T88','Complicações de cuidados médicos e cirúrgicos, não classificados em outra parte','Complicações cuidados médicos e cirúrgicos, NCOP');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('T90','T98','Seqüelas de traumatismos, de intoxicações e de outras conseqüências das causas externas','Seqüelas traum, intox e outr conseq causas extern');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V01','X59','Acidentes','Acidentes');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V01','V99','Acidentes de transporte','Acidentes de transporte');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V01','V09','Pedestre traumatizado em um acidente de transporte','Pedestre traumatizado em um acidente de transporte');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V10','V19','Ciclista traumatizado em um acidente de transporte','Ciclista traumatizado em um acidente de transporte');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V20','V29','Motociclista traumatizado em um acidente de transporte','Motociclista traumat em um acidente de transporte');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V30','V39','Ocupante de triciclo motorizado traumatizado em um acidente de transporte','Ocupante triciclo motorizado traumat acid transp');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V40','V49','Ocupante de um automóvel traumatizado em um acidente de transporte','Ocupante automóvel traumat acidente transporte');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V50','V59','Ocupante de uma caminhonete traumatizado em um acidente de transporte','Ocupante caminhonete traumat acidente transporte');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V60','V69','Ocupante de um veículo de transporte pesado traumatizado em um acidente de transporte','Ocupante veíc transp pesado traumat acid transp');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V70','V79','Ocupante de um ônibus traumatizado em um acidente de transporte','Ocupante ônibus traumat acidente de transporte');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V80','V89','Outros acidentes de transporte terrestre','Outros acidentes de transporte terrestre');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V90','V94','Acidentes de transporte por água','Acidentes de transporte por água');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V95','V97','Acidentes de transporte aéreo e espacial','Acidentes de transporte aéreo e espacial');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('V98','V99','Outros acidentes de transporte e os não especificados','Outros acidentes de transporte e os não especif');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('W00','X59','Outras causas externas de traumatismos acidentais','Outras causas externas de traumatismos acidentais');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('W00','W19','Quedas','Quedas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('W20','W49','Exposição a forças mecânicas inanimadas','Exposição a forças mecânicas inanimadas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('W50','W64','Exposição a forças mecânicas animadas','Exposição a forças mecânicas animadas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('W65','W74','Afogamento e submersão acidentais','Afogamento e submersão acidentais');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('W75','W84','Outros riscos acidentais à respiração','Outros riscos acidentais à respiração');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('W85','W99','Exposição à corrente elétrica, à radiação e às temperaturas e pressões extremas do ambiente','Expos corr elétr, radiação e temp press extrem amb');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('X00','X09','Exposição à fumaça, ao fogo e às chamas','Exposição à fumaça, ao fogo e às chamas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('X10','X19','Contato com uma fonte de calor ou com substâncias quentes','Contato com fonte de calor ou substâncias quentes');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('X20','X29','Contato com animais e plantas venenosos','Contato com animais e plantas venenosos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('X30','X39','Exposição às forças da natureza','Exposição às forças da natureza');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('X40','X49','Envenenamento [intoxicação] acidental por e exposição à substâncias nocivas','Envenenamento acidental e exposição subst nocivas');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('X50','X57','Excesso de esforços, viagens e privações','Excesso de esforços, viagens e privações');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('X58','X59','Exposição acidental a outros fatores e aos não especificados','Exposição acidental a outr fatores e aos não espec');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('X60','X84','Lesões autoprovocadas intencionalmente','Lesões autoprovocadas intencionalmente');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('X85','Y09','Agressões','Agressões');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Y10','Y34','Eventos (fatos) cuja intenção é indeterminada','Eventos (fatos) cuja intenção é indeterminada');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Y35','Y36','Intervenções legais e operações de guerra','Intervenções legais e operações de guerra');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Y40','Y84','Complicações de assistência médica e cirúrgica','Complicações de assistência médica e cirúrgica');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Y40','Y59','Efeitos adversos de drogas, medicamentos e substâncias biológicas usadas com finalidade terapêutica','Ef advers drog, medic e subst biológ finalid terap');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Y60','Y69','Acidentes ocorridos em pacientes durante a prestação de cuidados médicos e cirúrgicos','Acid ocorr pacientes prest cuid médicos e cirúrg');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Y70','Y82','Incidentes adversos durante atos diagnósticos ou terapêuticos associados ao uso de dispositivos (aparelhos) médicos','Incid advers atos diagn terap assoc disposit médic');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Y83','Y84','Reação anormal em paciente ou complicação tardia causadas por procedimentos cirúrgicos e outros procedimentos médicos sem menção de acidente ao tempo do procedimento','Reaç anorm compl tard proc cirúrg méd s/menç acid');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Y85','Y89','Seqüelas de causas externas de morbidade e de mortalidade','Seqüelas causas externas de morbidade e mortalidad');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Y90','Y98','Fatores suplementares relacionados com as causas de morbidade e de mortalidade classificados em outra parte','Fatores supl relac causas de morbid e mortalid COP');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Z00','Z13','Pessoas em contato com os serviços de saúde para exame e investigação','Pessoas contato serv saúde p/exame e investigação');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Z20','Z29','Pessoas com riscos potenciais à saúde relacionados com doenças transmissíveis','Pessoas c/riscos potenc saúde relac doenças transm');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Z30','Z39','Pessoas em contato com os serviços de saúde em circunstâncias relacionadas com a reprodução','Pessoas contato serv saúde circunst relac reprod');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Z40','Z54','Pessoas em contato com os serviços de saúde para procedimentos e cuidados específicos','Pessoas contato serv saúde proced e cuidados espec');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Z55','Z65','Pessoas com riscos potenciais à saúde relacionados com circunstâncias socioeconômicas e psicossociais','Pessoas c/risc potenc saúde relac circ socio psico');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Z70','Z76','Pessoas em contato com os serviços de saúde em outras circunstâncias','Pessoas em contato com serv saúde outras circunst');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('Z80','Z99','Pessoas com riscos potenciais à saúde relacionados com história familiar e pessoal e algumas afecções que influenciam o estado de saúde','Pess risc pot saúde hist fam pes afecç q infl saúd');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('U04','U04','Designação provisória de novas doenças de etiologia incerta','Designação prov novas doenças de etiologia incerta');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('U80','U89','Agentes bacterianos resistentes a antibióticos','Agentes bacterianos resistentes a antibióticos');
INSERT INTO codigodoenca(cidctgini, cidctgfim, ciddes, ciddesabr) VALUES ('U99','U99','CID 10ª Revisão não disponível','CID 10ª Revisão não disponível');














